version: '2'
services:
  escolaonline-app:
    image: escolaonline
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://escolaonline-postgresql:5432/EscolaOnline
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  escolaonline-postgresql:
    extends:
      file: postgresql.yml
      service: escolaonline-postgresql
