export enum TipoDebito {
  MENSALIDADE = 'MENSALIDADE',

  TAXA_MATERIAL = 'TAXA_MATERIAL',

  TAXA_MATRICULA = 'TAXA_MATRICULA',

  TAXA_DOCUMENTO = 'TAXA_DOCUMENTO',

  UNIFORME = 'UNIFORME',

  LIVRO = 'LIVRO',

  CANTINA = 'CANTINA',

  EVENTO = 'EVENTO',

  OUTROS = 'OUTROS',
}
