export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  TITULAR = 'ROLE_TITULAR',
  GERENTE = 'ROLE_GERENTE',
  PROFESSOR = 'ROLE_PROFESSOR',
  ALUNO = 'ROLE_ALUNO',
  RESPONSAVEL = 'ROLE_RESPONSAVEL'
}
